type Query {
  getFacilityOptions: AWSJSON @function(name: "FnGetFacilityOptions") @auth(rules: [{allow: public, provider: iam}])
  createCustomerQuote(payload: AWSJSON): AWSJSON @function(name: "FnCreateCustomerQuote") @auth(rules: [{allow: public, provider: iam}])
  calculatePackageOptions(quoteID: String): AWSJSON @function(name: "FnCalculatePackageOptions") @auth(rules: [{allow: public, provider: iam}])
  updateQuoteBudget(quoteID: String, budget: Float): AWSJSON @function(name: "FnUpdateQuoteBudget") @auth(rules: [{allow: public, provider: iam}])
  updateCustomerInfo(quoteID: String, customerInfo: AWSJSON): AWSJSON @function(name: "FnUpdateCustomerInfo") @auth(rules: [{allow: private, provider: userPools}])
  updateFacilityType(quoteID: String, facilityType: String): AWSJSON @function(name: "FnUpdateFacilityType") @auth(rules: [{allow: private, provider: userPools}])
  updateFloorInfo(quoteID: String, floorInfo: AWSJSON): AWSJSON @function(name: "FnUpdateFloorInfo") @auth(rules: [{allow: public, provider: iam}])
  confirmQuote(quoteID: String): AWSJSON @function(name: "FnConfirmQuote") @auth(rules: [{allow: public, provider: iam}])
  getQuote(quoteID: String): AWSJSON @function(name: "FnGetQuote") @auth(rules: [{allow: public, provider: iam}])
  updateQuoteRooms(quoteID: String, formInfo: AWSJSON): AWSJSON @function(name: "FnUpdateQuoteRooms") @auth(rules: [{allow: public, provider: iam}])
  updatePackageChoice(quoteID: String, packageInfo: AWSJSON): AWSJSON @function(name: "FnUpdatePackageChoice") @auth(rules: [{allow: public, provider: iam}])
  sendQuoteConfirmationEmail(quoteID: String): AWSJSON @function(name: "FnSendQuoteConfirmationEmail") @auth(rules: [{allow: public, provider: iam}])
}